import base64
import io
import os
import secrets
import sqlite3
from functools import wraps
from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse

import qrcode
from flask import (
    Flask,
    abort,
    g,
    redirect,
    render_template,
    request,
    session,
    url_for,
)

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # Local SQLite development does not need psycopg installed.
    psycopg = None
    dict_row = None


app = Flask(__name__)
app.config["DATABASE"] = os.environ.get("DATABASE_PATH", "analytics.db")
app.config["DATABASE_URL"] = os.environ.get("DATABASE_URL", "")
app.config["DB_BACKEND"] = os.environ.get(
    "DB_BACKEND", "postgres" if os.environ.get("DATABASE_URL") else "sqlite"
)
app.config["SECRET_KEY"] = os.environ.get("SECRET_KEY", "local-dev-secret-key")
app.config["PUBLIC_BASE_URL"] = os.environ.get("PUBLIC_BASE_URL", "").rstrip("/")

DEFAULT_UTM_VARIANTS = "\n".join(
    [
        "qr,offline",
        "poster,offline",
        "flyer,print",
    ]
)
UTM_FIELDS = ("utm_source", "utm_medium", "utm_campaign", "utm_term", "utm_content")


SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS short_links (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT NOT NULL UNIQUE,
    destination_url TEXT NOT NULL,
    title TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    legacy_tracked_link_id INTEGER UNIQUE,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS visits (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    short_link_id INTEGER NOT NULL,
    visited_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    utm_source TEXT,
    utm_medium TEXT,
    utm_campaign TEXT,
    utm_term TEXT,
    utm_content TEXT,
    referrer TEXT,
    user_agent TEXT,
    ip_address TEXT,
    browser TEXT,
    device_type TEXT,
    FOREIGN KEY (short_link_id) REFERENCES short_links (id)
);

CREATE INDEX IF NOT EXISTS idx_short_links_code ON short_links (code);
CREATE INDEX IF NOT EXISTS idx_visits_short_link_id ON visits (short_link_id);
CREATE INDEX IF NOT EXISTS idx_visits_visited_at ON visits (visited_at);
CREATE INDEX IF NOT EXISTS idx_visits_utm_campaign ON visits (utm_campaign);
"""

POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS short_links (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    destination_url TEXT NOT NULL,
    title TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    legacy_tracked_link_id INTEGER UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS visits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_link_id INTEGER NOT NULL REFERENCES short_links (id),
    visited_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    utm_source TEXT,
    utm_medium TEXT,
    utm_campaign TEXT,
    utm_term TEXT,
    utm_content TEXT,
    referrer TEXT,
    user_agent TEXT,
    ip_address TEXT,
    browser TEXT,
    device_type TEXT
);

CREATE INDEX IF NOT EXISTS idx_short_links_code ON short_links (code);
CREATE INDEX IF NOT EXISTS idx_visits_short_link_id ON visits (short_link_id);
CREATE INDEX IF NOT EXISTS idx_visits_visited_at ON visits (visited_at);
CREATE INDEX IF NOT EXISTS idx_visits_utm_campaign ON visits (utm_campaign);
"""


def db_backend() -> str:
    return app.config["DB_BACKEND"]


def get_db():
    if "db" not in g:
        if db_backend() == "postgres":
            if psycopg is None:
                raise RuntimeError("Install psycopg to use the Postgres backend.")
            if not app.config["DATABASE_URL"]:
                raise RuntimeError("DATABASE_URL is required for the Postgres backend.")
            g.db = psycopg.connect(app.config["DATABASE_URL"], row_factory=dict_row)
        else:
            g.db = sqlite3.connect(app.config["DATABASE"])
            g.db.row_factory = sqlite3.Row
    return g.db


@app.teardown_appcontext
def close_db(_error: Exception | None = None) -> None:
    db = g.pop("db", None)
    if db is not None:
        db.close()


def placeholders(query: str) -> str:
    if db_backend() == "postgres":
        return query.replace("?", "%s")
    return query


def execute(query: str, params: tuple = ()):
    return get_db().execute(placeholders(query), params)


def executescript(script: str) -> None:
    db = get_db()
    if db_backend() == "postgres":
        for statement in script.split(";"):
            if statement.strip():
                db.execute(statement)
    else:
        db.executescript(script)


def integrity_error() -> type[Exception]:
    if db_backend() == "postgres" and psycopg is not None:
        return psycopg.IntegrityError
    return sqlite3.IntegrityError


def table_exists(table_name: str) -> bool:
    if db_backend() == "postgres":
        row = execute(
            """
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name = ?
            """,
            (table_name,),
        ).fetchone()
    else:
        row = execute(
            "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?",
            (table_name,),
        ).fetchone()
    return row is not None


def init_db() -> None:
    executescript(POSTGRES_SCHEMA if db_backend() == "postgres" else SQLITE_SCHEMA)

    if db_backend() == "sqlite" and table_exists("tracked_links"):
        migrate_legacy_tracked_links()

    get_db().commit()


@app.before_request
def ensure_database() -> None:
    if not app.config.get("DB_INITIALIZED"):
        init_db()
        app.config["DB_INITIALIZED"] = True


def migrate_legacy_tracked_links() -> None:
    rows = execute(
        """
        SELECT id, destination_url, created_at
        FROM tracked_links
        ORDER BY id
        """
    ).fetchall()

    for row in rows:
        existing = execute(
            "SELECT id FROM short_links WHERE legacy_tracked_link_id = ?",
            (row["id"],),
        ).fetchone()
        if existing:
            continue

        code = unique_code(prefix=f"legacy{row['id']}")
        execute(
            """
            INSERT INTO short_links (
                code, destination_url, title, is_active,
                legacy_tracked_link_id, created_at
            )
            VALUES (?, ?, ?, 1, ?, ?)
            """,
            (
                code,
                strip_utm_params(row["destination_url"]),
                f"Imported tracked link {row['id']}",
                row["id"],
                row["created_at"],
            ),
        )


def normalize_url(raw_url: str) -> str:
    value = raw_url.strip()
    if not value:
        return ""

    parsed = urlparse(value)
    if not parsed.scheme:
        value = f"https://{value}"

    return value


def is_valid_url(value: str) -> bool:
    parsed = urlparse(value)
    return parsed.scheme in {"http", "https"} and bool(parsed.netloc)


def strip_utm_params(url: str) -> str:
    parsed = urlparse(url)
    query_params = [
        (key, value)
        for key, value in parse_qsl(parsed.query, keep_blank_values=True)
        if key not in UTM_FIELDS
    ]
    return urlunparse(parsed._replace(query=urlencode(query_params)))


def add_query_params(url: str, params: dict[str, str]) -> str:
    parsed = urlparse(url)
    query_params = dict(parse_qsl(parsed.query, keep_blank_values=True))
    query_params.update(
        {key: value.strip() for key, value in params.items() if value.strip()}
    )
    return urlunparse(parsed._replace(query=urlencode(query_params)))


def parse_utm_variants(raw_variants: str) -> list[dict[str, str]]:
    variants: list[dict[str, str]] = []

    for line in raw_variants.splitlines():
        stripped = line.strip()
        if not stripped:
            continue

        parts = [part.strip() for part in stripped.split(",")]
        if len(parts) != 2 or not all(parts):
            raise ValueError(
                "Each UTM variant must be on its own line as source,medium."
            )

        source, medium = parts
        variants.append(
            {
                "source": source,
                "medium": medium,
                "label": f"{source} / {medium}",
            }
        )

    if not variants:
        raise ValueError("Add at least one UTM variant to generate.")

    return variants


def generate_qr_base64(url: str) -> str:
    qr = qrcode.QRCode(box_size=10, border=4)
    qr.add_data(url)
    qr.make(fit=True)

    image = qr.make_image(fill_color="black", back_color="white")
    buffer = io.BytesIO()
    image.save(buffer, format="PNG")

    return base64.b64encode(buffer.getvalue()).decode("ascii")


def unique_code(prefix: str | None = None) -> str:
    if prefix:
        candidate = prefix
        suffix = 1
        while execute(
            "SELECT 1 FROM short_links WHERE code = ?", (candidate,)
        ).fetchone():
            suffix += 1
            candidate = f"{prefix}-{suffix}"
        return candidate

    while True:
        candidate = secrets.token_urlsafe(5).replace("-", "").replace("_", "")[:7]
        if not execute(
            "SELECT 1 FROM short_links WHERE code = ?", (candidate,)
        ).fetchone():
            return candidate


def create_short_link(destination_url: str, title: str = ""):
    for _attempt in range(5):
        code = unique_code()
        try:
            execute(
                """
                INSERT INTO short_links (code, destination_url, title)
                VALUES (?, ?, ?)
                """,
                (code, destination_url, title.strip() or None),
            )
        except integrity_error():
            get_db().rollback()
            continue

        get_db().commit()
        return execute("SELECT * FROM short_links WHERE code = ?", (code,)).fetchone()

    raise RuntimeError("Could not create a unique short code.")


def short_url_for(code: str) -> str:
    path = url_for("redirect_short_link", code=code)
    if app.config["PUBLIC_BASE_URL"]:
        return f"{app.config['PUBLIC_BASE_URL']}{path}"
    return url_for("redirect_short_link", code=code, _external=True)


def classify_browser(user_agent: str) -> str:
    ua = user_agent.lower()
    if "edg/" in ua:
        return "Edge"
    if "chrome/" in ua and "chromium" not in ua:
        return "Chrome"
    if "firefox/" in ua:
        return "Firefox"
    if "safari/" in ua and "chrome/" not in ua:
        return "Safari"
    if user_agent:
        return "Other"
    return "Unknown"


def classify_device(user_agent: str) -> str:
    ua = user_agent.lower()
    if "mobile" in ua or "iphone" in ua or "android" in ua:
        return "Mobile"
    if "ipad" in ua or "tablet" in ua:
        return "Tablet"
    if user_agent:
        return "Desktop"
    return "Unknown"


def client_ip() -> str:
    forwarded = request.headers.get("X-Forwarded-For", "")
    if forwarded:
        return forwarded.split(",", 1)[0].strip()
    return request.remote_addr or ""


def record_visit(link) -> None:
    user_agent = request.headers.get("User-Agent", "")
    values = {field: request.args.get(field, "").strip() or None for field in UTM_FIELDS}
    execute(
        """
        INSERT INTO visits (
            short_link_id, utm_source, utm_medium, utm_campaign,
            utm_term, utm_content, referrer, user_agent, ip_address,
            browser, device_type
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            link["id"],
            values["utm_source"],
            values["utm_medium"],
            values["utm_campaign"],
            values["utm_term"],
            values["utm_content"],
            request.referrer,
            user_agent,
            client_ip(),
            classify_browser(user_agent),
            classify_device(user_agent),
        ),
    )
    get_db().commit()


def analytics_password() -> str:
    return os.environ.get("ANALYTICS_PASSWORD", "")


def analytics_login_required(view):
    @wraps(view)
    def wrapped_view(*args, **kwargs):
        if not analytics_password():
            return render_template("analytics_login.html", password_missing=True), 503
        if not session.get("analytics_authenticated"):
            return redirect(url_for("analytics_login", next=request.path))
        return view(*args, **kwargs)

    return wrapped_view


def first_value(row) -> int:
    if row is None:
        return 0
    if isinstance(row, dict):
        return next(iter(row.values()))
    return row[0]


def scalar(query: str, params: tuple = ()) -> int:
    row = execute(query, params).fetchone()
    value = first_value(row)
    return value if value is not None else 0


@app.route("/", methods=["GET", "POST"])
def index():
    url = ""
    title = ""
    error = None
    result = None
    enable_utm_set = False
    generate_qrs = False
    utm_campaign = ""
    utm_variants = DEFAULT_UTM_VARIANTS

    if request.method == "POST":
        url = normalize_url(request.form.get("url", ""))
        title = request.form.get("title", "").strip()
        enable_utm_set = request.form.get("enable_utm_set") == "on"
        generate_qrs = request.form.get("generate_qrs") == "on"
        utm_campaign = request.form.get("utm_campaign", "").strip()
        utm_variants = request.form.get("utm_variants", DEFAULT_UTM_VARIANTS).strip()

        if not url:
            error = "Enter a destination link."
        elif not is_valid_url(url):
            error = "Enter a valid http or https link."
        elif enable_utm_set and not utm_campaign:
            error = "Enter a campaign name to generate UTM links."
        else:
            try:
                variants = parse_utm_variants(utm_variants) if enable_utm_set else []
            except ValueError as exc:
                error = str(exc)
            else:
                link = create_short_link(url, title)
                base_short_url = short_url_for(link["code"])
                generated_variants = []

                for variant in variants:
                    variant_url = add_query_params(
                        base_short_url,
                        {
                            "utm_source": variant["source"],
                            "utm_medium": variant["medium"],
                            "utm_campaign": utm_campaign,
                        },
                    )
                    generated_variants.append(
                        {
                            **variant,
                            "url": variant_url,
                            "qr_image": generate_qr_base64(variant_url)
                            if generate_qrs
                            else "",
                        }
                    )

                result = {
                    "code": link["code"],
                    "destination_url": link["destination_url"],
                    "short_url": base_short_url,
                    "qr_image": generate_qr_base64(base_short_url)
                    if generate_qrs and not generated_variants
                    else "",
                    "variants": generated_variants,
                }

    return render_template(
        "index.html",
        url=url,
        title=title,
        error=error,
        result=result,
        enable_utm_set=enable_utm_set,
        generate_qrs=generate_qrs,
        utm_campaign=utm_campaign,
        utm_variants=utm_variants,
    )


@app.route("/s/<code>")
def redirect_short_link(code: str):
    link = execute(
        "SELECT * FROM short_links WHERE code = ? AND is_active = 1", (code,)
    ).fetchone()
    if not link:
        abort(404)

    record_visit(link)
    utm_values = {
        field: request.args.get(field, "").strip()
        for field in UTM_FIELDS
        if request.args.get(field, "").strip()
    }
    return redirect(add_query_params(link["destination_url"], utm_values), code=302)


@app.route("/analytics/login", methods=["GET", "POST"])
def analytics_login():
    if not analytics_password():
        return render_template("analytics_login.html", password_missing=True), 503

    error = None
    if request.method == "POST":
        if request.form.get("password", "") == analytics_password():
            session["analytics_authenticated"] = True
            return redirect(request.args.get("next") or url_for("analytics_dashboard"))
        error = "That password did not match."

    return render_template("analytics_login.html", error=error, password_missing=False)


@app.route("/analytics/logout")
def analytics_logout():
    session.pop("analytics_authenticated", None)
    return redirect(url_for("analytics_login"))


@app.route("/analytics")
@analytics_login_required
def analytics_dashboard():
    top_links = execute(
        """
        SELECT
            short_links.code,
            short_links.title,
            short_links.destination_url,
            COUNT(visits.id) AS visit_count,
            MAX(visits.visited_at) AS last_visit
        FROM short_links
        LEFT JOIN visits ON visits.short_link_id = short_links.id
        GROUP BY short_links.id
        ORDER BY visit_count DESC, short_links.created_at DESC
        LIMIT 10
        """
    ).fetchall()
    daily_visits = execute(
        """
        SELECT DATE(visited_at) AS visit_date, COUNT(*) AS visit_count
        FROM visits
        GROUP BY DATE(visited_at)
        ORDER BY visit_date DESC
        LIMIT 14
        """
    ).fetchall()
    recent_visits = execute(
        """
        SELECT visits.*, short_links.code, short_links.title, short_links.destination_url
        FROM visits
        JOIN short_links ON short_links.id = visits.short_link_id
        ORDER BY visits.visited_at DESC
        LIMIT 25
        """
    ).fetchall()

    return render_template(
        "analytics_dashboard.html",
        total_visits=scalar("SELECT COUNT(*) FROM visits"),
        visits_today=visits_today_count(),
        total_links=scalar("SELECT COUNT(*) FROM short_links"),
        top_links=top_links,
        daily_visits=list(reversed(daily_visits)),
        top_campaigns=top_dimension("utm_campaign"),
        top_sources=top_dimension("utm_source"),
        top_mediums=top_dimension("utm_medium"),
        recent_visits=recent_visits,
    )


def visits_today_count() -> int:
    if db_backend() == "postgres":
        return scalar("SELECT COUNT(*) FROM visits WHERE DATE(visited_at) = CURRENT_DATE")
    return scalar("SELECT COUNT(*) FROM visits WHERE DATE(visited_at) = DATE('now')")


def top_dimension(column: str, short_link_id: int | None = None) -> list:
    if column not in UTM_FIELDS:
        raise ValueError("Unsupported analytics column.")

    params: tuple = ()
    link_filter = ""
    if short_link_id is not None:
        link_filter = "AND short_link_id = ?"
        params = (short_link_id,)

    return execute(
        f"""
        SELECT {column} AS label, COUNT(*) AS visit_count
        FROM visits
        WHERE {column} IS NOT NULL AND {column} != '' {link_filter}
        GROUP BY {column}
        ORDER BY visit_count DESC, label ASC
        LIMIT 10
        """,
        params,
    ).fetchall()


@app.route("/analytics/link/<code>")
@analytics_login_required
def analytics_link_detail(code: str):
    link = execute("SELECT * FROM short_links WHERE code = ?", (code,)).fetchone()
    if not link:
        abort(404)

    daily_visits = execute(
        """
        SELECT DATE(visited_at) AS visit_date, COUNT(*) AS visit_count
        FROM visits
        WHERE short_link_id = ?
        GROUP BY DATE(visited_at)
        ORDER BY visit_date DESC
        LIMIT 14
        """,
        (link["id"],),
    ).fetchall()
    recent_visits = execute(
        """
        SELECT *
        FROM visits
        WHERE short_link_id = ?
        ORDER BY visited_at DESC
        LIMIT 50
        """,
        (link["id"],),
    ).fetchall()

    return render_template(
        "analytics_link.html",
        link=link,
        short_url=short_url_for(code),
        total_visits=scalar(
            "SELECT COUNT(*) FROM visits WHERE short_link_id = ?", (link["id"],)
        ),
        daily_visits=list(reversed(daily_visits)),
        top_campaigns=top_dimension("utm_campaign", link["id"]),
        top_sources=top_dimension("utm_source", link["id"]),
        top_mediums=top_dimension("utm_medium", link["id"]),
        recent_visits=recent_visits,
    )


if __name__ == "__main__":
    with app.app_context():
        init_db()
        app.config["DB_INITIALIZED"] = True
    app.run(debug=True)
